name: utils
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pytest
  - pre-commit
  - tqdm
  - colorlog
  - requests
  - pandas
  - click
  - google-cloud-storage
  - google-api-python-client
  - geopandas
  - fsspec
  - aiohttp
  - pip:
    - python-dotenv
    - Pillow
