name: utils
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - tqdm
  - colorlog
  - requests
  - pandas
  - click
  - google-cloud-storage
  - pyshp
  - pip:
      - pytest
      - pre-commit
      - geobeam
